import { Tag } from "../../../types/Response";

const tags: Tag[] = [
  {
    count: 10,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 1",
  },
  {
    count: 5,
    has_synonyms: false,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 2",
  },
  {
    count: 20,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 3",
  },
  {
    count: 8,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 4",
  },
  {
    count: 15,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 5",
  },
  {
    count: 3,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: true,
    name: "Tag 6",
  },
  {
    count: 12,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 7",
  },
  {
    count: 9,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 8",
  },
  {
    count: 18,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 9",
  },
  {
    count: 7,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 10",
  },
  {
    count: 25,
    has_synonyms: false,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 11",
  },
  {
    count: 14,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 12",
  },
  {
    count: 11,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: true,
    name: "Tag 13",
  },
  {
    count: 6,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 14",
  },
  {
    count: 22,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 15",
  },
  {
    count: 17,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 16",
  },
  {
    count: 4,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 17",
  },
  {
    count: 19,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 18",
  },
  {
    count: 13,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 19",
  },
  {
    count: 16,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 20",
  },
  {
    count: 21,
    has_synonyms: false,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 21",
  },
  {
    count: 27,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 22",
  },
  {
    count: 30,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 23",
  },
  {
    count: 24,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 24",
  },
  {
    count: 28,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 25",
  },
  {
    count: 35,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 26",
  },
  {
    count: 32,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 27",
  },
  {
    count: 29,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 28",
  },
  {
    count: 33,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 29",
  },
  {
    count: 36,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 30",
  },
  {
    count: 38,
    has_synonyms: false,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 31",
  },
  {
    count: 37,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 32",
  },
  {
    count: 34,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 33",
  },
  {
    count: 39,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 34",
  },
  {
    count: 40,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 35",
  },
  {
    count: 45,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 36",
  },
  {
    count: 41,
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    name: "Tag 37",
  },
  {
    count: 48,
    has_synonyms: false,
    is_moderator_only: true,
    is_required: false,
    name: "Tag 38",
  },
  {
    count: 44,
    has_synonyms: true,
    is_moderator_only: false,
    is_required: true,
    name: "Tag 39",
  },
  {
    count: 42,
    has_synonyms: true,
    is_moderator_only: true,
    is_required: true,
    name: "Tag 40",
  },
];

export default tags;
